# Generated by Django 4.1.1 on 2022-09-28 22:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_dvd_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluguel',
            name='funcionario',
            field=models.ForeignKey(db_column='id_funcionario', on_delete=django.db.models.deletion.DO_NOTHING, related_name='alugueis', to='core.funcionario'),
        ),
    ]
